### ISSUE TITLE
Update Start of Game

### ISSUE THREAD

**Issue by mberlanga** [UCSB-CS56-Projects/cs56-games-roguelike#100]
Now that diagonal movement and "linger" is added to the movement keys, the start of the screen should tell the user the new options on how to move. [25-50pts?]
![updatestartofgame](https://user-images.githubusercontent.com/20020479/33411396-4941656c-d53a-11e7-9438-80223f1faf66.png)

**Comment by xavierholt** [comment]
Fixed by https://github.com/UCSB-CS56-Projects/cs56-games-roguelike/pull/113.

+50 XP
