### ISSUE TITLE
Score No Longer Adds

### ISSUE THREAD

**Issue by mberlanga** [UCSB-CS56-Projects/cs56-games-roguelike#101]
With all the monsters slain as you go, wouldn't the player get a sense of accomplishment from seeing their cumulative score at the end? The newest commit to the master must have changed this by accident. The score now resets with each level.  Make the score keep track again.

![scoredoesnotadd1](https://user-images.githubusercontent.com/20020479/33412467-59c17354-d540-11e7-97aa-c1127595e6ae.png)

![scoredoesnotadd2](https://user-images.githubusercontent.com/20020479/33412468-59d6c100-d540-11e7-9f95-81dd75bc9432.png)

**Comment by xavierholt** [comment]
Fixed in https://github.com/UCSB-CS56-Projects/cs56-games-roguelike/pull/117.

+100 XP
