### ISSUE TITLE
Too Many Ghosts!

### ISSUE THREAD

**Issue by mberlanga** [UCSB-CS56-Projects/cs56-games-roguelike#103]
The group from a year ago must have used an editor that left these residual "ghost" files. They are a waste of space, delete them.

![toomanyghosts](https://user-images.githubusercontent.com/20020479/33412739-44321bcc-d542-11e7-9f22-ea7f5de389fe.png)

**Comment by xavierholt** [comment]
Fixed by https://github.com/UCSB-CS56-Projects/cs56-games-roguelike/pull/114.

+50 XP
