### ISSUE TITLE
Instructions need update (+ not scary enough to spook player)

### ISSUE THREAD

**Issue by mberlanga** [UCSB-CS56-Projects/cs56-games-roguelike#106]
The old instructions window is out of date and needs updated instructions given that there is diagonal movement and a "linger" feature. Also it's a giant wall of text and should be formatted to be easier on the eyes. Lastly, these instructions make me fall asleep, make them spookier.

![oldinstructions](https://user-images.githubusercontent.com/20020479/33459861-7b236426-d5e0-11e7-98c8-1150bf95f68e.png)

**Comment by xavierholt** [comment]
Fixed in https://github.com/UCSB-CS56-Projects/cs56-games-roguelike/pull/119.  These are great!

+ 50 XP
