### ISSUE TITLE
Fix the losing screen bug

### ISSUE THREAD

**Issue by mberlanga** [UCSB-CS56-Projects/cs56-games-roguelike#107]
When the player dies, the screen just shows the entire map lit up from the darkness, this is most definitely a bug. Where's the highscore? Where your final score? This losing screen is supposed to show up. Fix this glitch.

About to Die:
![screenbeforedeathlosingscreen](https://user-images.githubusercontent.com/20020479/33463706-e59c726c-d5f3-11e7-919a-653d0106c56d.png)
At Death:
![notrightlosingscreen](https://user-images.githubusercontent.com/20020479/33463793-4668c01e-d5f4-11e7-9da0-2b61723c4af9.png)

**Comment by xavierholt** [comment]
Fixed in https://github.com/UCSB-CS56-Projects/cs56-games-roguelike/pull/121.  Created https://github.com/UCSB-CS56-Projects/cs56-games-roguelike/issues/120 to deal with the main high scores screen saying I lost (dunno if it did that before or not).

+50 XP
