### ISSUE TITLE
Continue menu music through window changes

### ISSUE THREAD

**Issue by aberlanga** [ucsb-cs56-projects/cs56-games-roguelike#111]
Currently in the main menu if you open any of the other windows, instructions or highscore, the music will reset upon closing the highscore or instruction window. Main Menu music should be maintained until a play game window starts. This is because the window closed function is overridden. A function that checks whether the music is still playing and accounts for this should fix it.

**Comment by xavierholt** [comment]
F17 OK: 100 XP

**Comment by brianslee** [comment]
W18 Ok 100 Points

**Comment by brianslee** [comment]
Fixed
Closed W18
