### ISSUE TITLE
Add Options Button

### ISSUE THREAD

**Issue by aberlanga** [ucsb-cs56-projects/cs56-games-roguelike#112]
Players may want music or sound effects volume to be muted or adjusted.  They may also want the difficulty of the game to be changed. An Options menu would make player experience better. This would involve making an options menu and button within the main menu to access it. This would require additional functions to adjust volume and difficulty.

**Comment by xavierholt** [comment]
Teams working on this might want to split it into smaller issues (one for volume, one for difficulty, etc.) to make it easier to get partial points.

F17 OK: 200 XP

**Comment by brianslee** [comment]
W18 Ok 200 Points

**Comment by brianslee** [comment]
Implemented
Closed W18
