### ISSUE TITLE
Better Messaging on Item Pickup

### ISSUE THREAD

**Issue by yashrane** [ucsb-cs56-projects/cs56-games-roguelike#125]
When you pick up an item, it would be better to display the specific item picked up and its effect. Currently, it only has a generic "item picked up" message in the lower left corner.

**Comment by johnnyzhang1738** [comment]
F17 OK (100 points)

**Comment by brianslee** [comment]
W18 Ok (100 Points)

**Comment by brianslee** [comment]
Fixed
Closed W18
