### ISSUE TITLE
Create a Gui

### ISSUE THREAD

**Issue by HMCodingSnowMan** [UCSB-CS56-Projects/cs56-games-roguelike#13]
Right now the game just starts by telling the user what to do. 
What should happen is that it should have a starting menu that says:

The title (Roguelike CS56 or give it a name)
Play
How to play
Exit

and anything else you can think of that would look nice in this gui.
Also instead of ending the game with the high score make it so it asks Play again
and it would start the game over.

~estimated 200

**Comment by dcwang** [comment]
Created GUI
