### ISSUE TITLE
Add items to the game

### ISSUE THREAD

**Issue by rick-lee** [UCSB-CS56-Projects/cs56-games-roguelike#17]
Create a purpose for the current items available and/or create more items that assist or harm the player.

Items that currently exist:
Beef
HealthPotion
Poison

Figure out how the player will obtain these items. 

Ideas:
Items randomly spawn on the ground
Items have a change to drop when defeating monsters

~estimated 250

**Comment by dcwang** [comment]
Items implemented, but still kind of buggy
