### ISSUE TITLE
A more detailed explanation (based on "compare/contrast" with Wikipedia entry)

### ISSUE THREAD

**Issue by pconrad** [UCSB-CS56-Projects/cs56-games-roguelike#19]
The wikipedia entry for Roguelike has a detailed description of some of the classic design and game elements of Roguelikes, as well as a description of how Roguelike's can vary:

http://en.wikipedia.org/wiki/Roguelike

Using this description, as well as any other sources you can find and cite, update the README.md with a description of both:

1. The current structure of the game:
    * what features are present, including a detailed description of how to play the game (what each button does, what each letter on the screen represents, goal of the game, strategy for successful play).
    * An description of whether it currently a "classic" or "Berlin" style Roguelike, or incorporates later styles of game design)
2. Where the game could be taken next, based on either issues already open in the repository, or new issues that could be added.  (You may like to add those issues and make reference to them as apporpriate---more points may be awarded if suitable issues are generated and approved by a mentor/TA/instructor.)

~estimated 200

**Comment by dcwang** [comment]
Added a features and gameplay guide section in the README
