### ISSUE TITLE
Add rooms and corridors

### ISSUE THREAD

**Issue by dcwang** [UCSB-CS56-Projects/cs56-games-roguelike#21]
Currently each level of the game looks the same, a plain rectangular grid. The original Rogue had rooms with corridors connecting them.

**Comment by dcwang** [comment]
Points estimate: 300?

**Comment by MadRubicant** [comment]
F16 OK (300 pts)

**Comment by xavierholt** [comment]
This is pretty vague.  Closing in favor of https://github.com/UCSB-CS56-Projects/cs56-games-roguelike/issues/55 and https://github.com/UCSB-CS56-Projects/cs56-games-roguelike/issues/59.
