### ISSUE TITLE
Items icons disappear

### ISSUE THREAD

**Issue by dcwang** [UCSB-CS56-Projects/cs56-games-roguelike#22]
When an item is dropped immediately after you kill a monster, it will appear on the screen. However, as soon as you make your next move, the item will "disappear" and be replaced by a blank space on the screen. It is still "there" logic-wise, meaning if you go back to that "empty" spot, you will consume the item. 

I believe the issue lies somewhere in RogueController.java and/or RoguePanel.java.

Points estimate: 200

**Comment by dcoffill** [comment]
Approved
