### ISSUE TITLE
Add a "final boss" monster to the game that appears at the end of every level or every other level

### ISSUE THREAD

**Issue by Ishjot** [UCSB-CS56-Projects/cs56-games-roguelike#34]
When clearing a level there could be a battle with a much more difficult monster. Create a new class that inherits from Monster.java.

Estimated points - 250

**Comment by arda-** [comment]
W16 OK

**Comment by MadRubicant** [comment]
F16 CLOSED: All combat in the game is identical; all a large boss monster would do is be a giant bag of health to kill or die to, depending entirely on your stats. The game requires mechanics, like usable items, before adding bosses.
