### ISSUE TITLE
Javadoc Cleanup

### ISSUE THREAD

**Issue by MadRubicant** [UCSB-CS56-Projects/cs56-games-roguelike#37]
There are 43 errors and 60 warnings generated when building the javadocs, mostly related to the XML comments not matching the code. Fix these

50 pts

**Comment by MadRubicant** [comment]
F16 OK (50 pts)

**Comment by xavierholt** [comment]
Closing in favor of https://github.com/UCSB-CS56-Projects/cs56-games-roguelike/issues/61.
