### ISSUE TITLE
Improved UI

### ISSUE THREAD

**Issue by MadRubicant** [ucsb-cs56-projects/cs56-games-roguelike#39]
There are various UI improvements that could be made. For example, the ability to start a new game immediately after a prior one without closing the game window. ~Another is the ability to pass your turn.~

100 pts

**Comment by MadRubicant** [comment]
F16 OK (100 pts)

**Comment by xavierholt** [comment]
Removing the "pass" feature from this ticket in favor of https://github.com/UCSB-CS56-Projects/cs56-games-roguelike/issues/71.

**Comment by brianslee** [comment]
W18 Ok 100 Pts

**Comment by brianslee** [comment]
Fixed W18.
