### ISSUE TITLE
Weird Interaction Between Monsters and Walls

### ISSUE THREAD

**Issue by max-devisser** [UCSB-CS56-Projects/cs56-games-roguelike#56]
When a monster tries moving into a space that contains a wall, the character "image" of the monster disappears, and nothing is drawn in the space the monster is/should be. (est: 150 pts)

**Comment by MadRubicant** [comment]
F16 OK (150 pts)

**Comment by xavierholt** [comment]
Dropping the points on this one:

100 XP

**Comment by xavierholt** [comment]
Fixed by https://github.com/UCSB-CS56-Projects/cs56-games-roguelike/pull/88.
