### ISSUE TITLE
Player Can Jump Over Walls and Monsters with Elixir Active

### ISSUE THREAD

**Issue by max-devisser** [UCSB-CS56-Projects/cs56-games-roguelike#58]
When moving with an elixir, the code checks only if the player can move to the space 2 (or 3 or 4..) ahead, and does not check if it can move through the spaces in between. (est: 100 pts)

**Comment by MadRubicant** [comment]
F16 OK (100 pts)

**Comment by xavierholt** [comment]
Would be fixed by https://github.com/UCSB-CS56-Projects/cs56-games-roguelike/issues/63, if you choose to accept it...
