### ISSUE TITLE
Fix Javadoc Comments

### ISSUE THREAD

**Issue by max-devisser** [UCSB-CS56-Projects/cs56-games-roguelike#61]
Many methods don't have javadoc comments, and some are out of date. (est: 100 pts)

**Comment by MadRubicant** [comment]
F16 OK (100 pts)

**Comment by xavierholt** [comment]
Bonus points (50 XP) if you add leading asterisks to the existing comments and make my editor less pink.
<img width="414" alt="screen shot 2017-10-01 at 11 01 11 am" src="https://user-images.githubusercontent.com/1435765/31057461-fb42e7ee-a697-11e7-8281-e273b0c67139.png">

**Comment by xavierholt** [comment]
Fixed in https://github.com/UCSB-CS56-Projects/cs56-games-roguelike/pull/116 (including leading newlines).

+150 XP
