### ISSUE TITLE
Fix the Title Screen

### ISSUE THREAD

**Issue by xavierholt** [ucsb-cs56-projects/cs56-games-roguelike#64]
As much as I love white buttons, this is hardly a great first impression...

50 XP

<img width="362" alt="screen shot 2017-10-01 at 11 18 44 am" src="https://user-images.githubusercontent.com/1435765/31057611-699d4502-a69a-11e7-960b-6f122e5600ce.png">

**Comment by brianslee** [comment]
Fixed.
W18 Closed
