### ISSUE TITLE
Longer Movements

### ISSUE THREAD

**Issue by xavierholt** [ucsb-cs56-projects/cs56-games-roguelike#72]
There's an awful lot of button pressing required to move around.  Make my fingers hurt less.

Basic (50 XP):  Listen for "key repeat" events and move on those.

Better (100 XP):  Implement a move queue.  If I press, say <kbd>Shift</kbd> + <kbd>A</kbd>, ten left moves are added to the queue.  If there are any moves in the queue, use one instead of waiting for user input.

Best (200 XP):  Implement the move queue as above, but clear it when something interesting happens (like if you hit a wall or see a monster).

**Comment by brianslee** [comment]
Not really the best idea in terms of game development.
W18 closed
