### ISSUE TITLE
Fix Indentation

### ISSUE THREAD

**Issue by xavierholt** [ucsb-cs56-projects/cs56-games-roguelike#74]
There's all sorts of gross indentation.  Tabs mixed with spaces.  Trailing spaces.  Fix it.

50 XP

**Comment by xavierholt** [comment]
Protip:  Check out `astyle` (http://astyle.sourceforge.net/astyle.html).

**Comment by brianslee** [comment]
W18 Ok 50 points

**Comment by brianslee** [comment]
Done
Closed W18
