### ISSUE TITLE
Multiple Game/Instruction/Highscore Instances

### ISSUE THREAD

**Issue by mberlanga** [UCSB-CS56-Projects/cs56-games-roguelike#79]
As a player, I am able to create as many game instances as I want by pressing "Play," "instructions", and "View Highscores." Code should probably be implemented to reduce these windows down to one each.

**Comment by xavierholt** [comment]
Fixed in https://github.com/UCSB-CS56-Projects/cs56-games-roguelike/pull/121/files.

+100 XP
