### ISSUE TITLE
Moving Into a Wall makes You and Monsters take a Turn 

### ISSUE THREAD

**Issue by mberlanga** [UCSB-CS56-Projects/cs56-games-roguelike#87]
Most walls don't have magic time properties when you touch them, neither should these walls. This could be argued to be a feature instead of a bug but I'm treating it as a bug. If a "linger" button is implemented then there is no need to run into a wall anymore. 

1) Let the user know that running into a wall does nothing for them 
and 
2) Make it so time doesn't move forward for player or monster (no one takes a turn).

**Comment by xavierholt** [comment]
Looks like this is fixed by https://github.com/UCSB-CS56-Projects/cs56-games-roguelike/pull/88

Tentative 50 XP.
